"""Abstract base class for LLM inference clients."""

from abc import ABC, abstractmethod
from typing import Generator


class BaseLLMClient(ABC):
    """Abstract interface for language model inference."""

    @abstractmethod
    def generate(self, prompt: str, system_prompt: str | None = None) -> str:
        """Generates text completion for the provided prompt."""
        pass

    @abstractmethod
    def generate_stream(
        self, prompt: str, system_prompt: str | None = None
    ) -> Generator[str, None, None]:
        """Yields text tokens as they are generated by the model."""
        pass

    async def agenerate(self, prompt: str, system_prompt: str | None = None) -> str:
        """Asynchronously generates text completion for the provided prompt."""
        return self.generate(prompt, system_prompt)

    async def agenerate_stream(self, prompt: str, system_prompt: str | None = None):
        """Asynchronously yields text tokens as they are generated by the model."""
        for token in self.generate_stream(prompt, system_prompt):
            yield token

    @property
    @abstractmethod
    def model_name(self) -> str:
        """Returns the model identifier."""
        pass

