"""Resilient HTTP client for Sarvam AI inference API (GLM-5.3)."""

import json
import time
from typing import Any, Generator
import httpx
from tenacity import (
    retry,
    retry_if_exception,
    stop_after_attempt,
    wait_exponential,
)

from src.core.exceptions import LLMClientError
from src.core.logging import setup_logger
from src.llm.base import BaseLLMClient

logger = setup_logger(__name__)


def _is_retryable_error(exception: BaseException) -> bool:
    """Checks if an error is transient and should trigger a retry."""
    if isinstance(exception, (httpx.ConnectError, httpx.TimeoutException, httpx.NetworkError)):
        return True
    if isinstance(exception, httpx.HTTPStatusError):
        # Retry on Rate Limit (429) and Server Errors (5xx)
        return exception.response.status_code in {429, 500, 502, 503, 504}
    return False


class SarvamGLMClient(BaseLLMClient):
    """Client for querying GLM-5.3 via Sarvam AI API."""

    def __init__(
        self,
        api_key: str,
        base_url: str = "https://api.sarvam.ai",
        model: str = "glm5.3",
        temperature: float = 0.2,
        max_tokens: int = 2048,
        timeout: float = 60.0,
    ) -> None:
        self.api_key = api_key.strip()
        self.base_url = base_url.rstrip("/")
        self._model = model
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.timeout = timeout

        self._endpoint = f"{self.base_url}/v2/chat/completions"
        self._client = httpx.Client(timeout=self.timeout)

    @property
    def model_name(self) -> str:
        return self._model

    def generate(self, prompt: str, system_prompt: str | None = None) -> str:
        """Executes inference call to Sarvam AI."""
        if not self.api_key or self.api_key.startswith("your_sarvam"):
            raise LLMClientError(
                "SARVAM_API_KEY is not configured or contains placeholder text. "
                "Please add your active Sarvam AI key in the .env file."
            )

        messages: list[dict[str, str]] = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        payload: dict[str, Any] = {
            "model": self._model,
            "messages": messages,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
        }

        headers = {
            "api-subscription-key": self.api_key,
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

        try:
            return self._call_api_with_retry(payload, headers)
        except Exception as e:
            if isinstance(e, LLMClientError):
                raise
            raise LLMClientError(f"Failed to generate response from Sarvam AI: {e}") from e

    @retry(
        reraise=True,
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=1.5, min=2, max=10),
        retry=retry_if_exception(_is_retryable_error),
    )
    def _call_api_with_retry(self, payload: dict[str, Any], headers: dict[str, str]) -> str:
        logger.debug(f"Sending request to Sarvam endpoint: {self._endpoint} (model: {self._model})")
        response = self._client.post(self._endpoint, json=payload, headers=headers)

        if response.status_code != 200:
            logger.error(
                f"Sarvam API error: HTTP {response.status_code} - {response.text}"
            )
            response.raise_for_status()

        data = response.json()
        try:
            content = data["choices"][0]["message"]["content"]
            return content.strip()
        except (KeyError, IndexError) as err:
            raise LLMClientError(
                f"Unexpected response format from Sarvam API: {data}"
            ) from err

    def generate_stream(
        self, prompt: str, system_prompt: str | None = None
    ) -> Generator[str, None, None]:
        """Streams text tokens generated by Sarvam AI in real-time."""
        if not self.api_key or self.api_key.startswith("your_sarvam"):
            raise LLMClientError(
                "SARVAM_API_KEY is not configured or contains placeholder text."
            )

        messages: list[dict[str, str]] = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        payload: dict[str, Any] = {
            "model": self._model,
            "messages": messages,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
            "stream": True,
        }

        headers = {
            "api-subscription-key": self.api_key,
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

        try:
            with self._client.stream("POST", self._endpoint, json=payload, headers=headers) as response:
                if response.status_code != 200:
                    err_text = response.read().decode("utf-8")
                    raise LLMClientError(
                        f"Sarvam API streaming error: HTTP {response.status_code} - {err_text}"
                    )
                for line in response.iter_lines():
                    if not line:
                        continue
                    if line.startswith("data: "):
                        data_str = line[6:].strip()
                        if data_str == "[DONE]":
                            break
                        try:
                            parsed = json.loads(data_str)
                            choices = parsed.get("choices", [])
                            if choices:
                                delta = choices[0].get("delta", {})
                                token = delta.get("content", "")
                                if token:
                                    yield token
                        except json.JSONDecodeError:
                            continue
        except Exception as e:
            if isinstance(e, LLMClientError):
                raise
            raise LLMClientError(f"Failed during streaming generation from Sarvam: {e}") from e

    def close(self) -> None:
        """Closes underlying HTTP client."""
        self._client.close()


class MockLLMClient(BaseLLMClient):
    """Mock client used for automated unit tests and offline testing."""

    def __init__(self, model_name: str = "mock-glm5.3", canned_response: str | None = None) -> None:
        self._model_name = model_name
        self.canned_response = canned_response

    @property
    def model_name(self) -> str:
        return self._model_name

    def generate(self, prompt: str, system_prompt: str | None = None) -> str:
        if self.canned_response:
            return self.canned_response
        return (
            "A contribution of **₹35,000 / US$365** can support approximately **500 children** in one school.\n\n"
            "Your contribution provides children with access to structured digital-skills learning through the Spoken Tutorial approach."
        )

    def generate_stream(
        self, prompt: str, system_prompt: str | None = None
    ) -> Generator[str, None, None]:
        full_text = self.generate(prompt, system_prompt)
        words = full_text.split(" ")
        for word in words:
            time.sleep(0.02)
            yield word + " "
