"""Domain schemas for RAG responses and citations."""

from pydantic import BaseModel, Field


class Citation(BaseModel):
    """Source attribution for generated claims."""

    chunk_id: str = Field(..., description="Unique ID of the source chunk")
    section: str = Field(..., description="Section title where information was found")
    question_number: int | None = Field(None, description="Original question number in FAQ")
    question_text: str | None = Field(None, description="Original FAQ question title")
    excerpt: str = Field(..., description="Brief relevant excerpt from the source text")


class RAGResponse(BaseModel):
    """Complete structured response generated by the RAG system."""

    query: str = Field(..., description="Original user question")
    answer: str = Field(..., description="Direct, concise, factually grounded answer")
    champion_talking_point: str | None = Field(
        None,
        description="Conversational pitch tailored for Champions speaking to supporters",
    )
    citations: list[Citation] = Field(default_factory=list, description="List of source citations")
    model_used: str = Field(..., description="LLM model identifier used for generation")
    is_fallback: bool = Field(
        default=False,
        description="True if query could not be answered from the document",
    )
    fallback_contacts: list[str] = Field(
        default_factory=lambda: ["sujathan@wheelsglobal.org", "saisudha@edupyramids.org"],
        description="Official contacts to reach out to if information is outside document scope",
    )
